export function ToolsHelp() {
  return (
    <div className="h-full p-4 overflow-auto">
      <div className="space-y-6">

        {/* Layout Overview */}
        <div>
          <h3 className="text-lg font-medium text-white mb-3">Session Workspace</h3>
          <p className="text-sm text-neutral-400 mb-4">
            The workspace is split into three areas. You can drag the separator to resize, or collapse either panel using the chevron buttons that appear on hover. Double-click the separator to reset to 50/50.
          </p>
          <div className="space-y-3">
            <div className="p-3 rounded-lg bg-neutral-900/50 border border-neutral-800">
              <div className="text-sm font-medium text-purple-400 mb-1">Left Sidebar</div>
              <p className="text-xs text-neutral-500">
                Tool selector. Main tools at top, utility tools (Help, Data Input, Logs, RAG) at bottom.
              </p>
            </div>
            <div className="p-3 rounded-lg bg-neutral-900/50 border border-neutral-800">
              <div className="text-sm font-medium text-cyan-400 mb-1">Center Panel</div>
              <p className="text-xs text-neutral-500">
                Active tool workspace. Chat with the AI tutor, draw on the canvas, take notes, search Grokipedia, or review prep materials.
              </p>
            </div>
            <div className="p-3 rounded-lg bg-neutral-900/50 border border-neutral-800">
              <div className="text-sm font-medium text-blue-400 mb-1">Right Panel &mdash; Student Monitoring</div>
              <p className="text-xs text-neutral-500">
                Guiding tasks (probes) on the left half, session plan with steps on the right half. Probes are generated by an AI that listens to your audio and monitors your actions.
              </p>
            </div>
          </div>
        </div>

        {/* Tools */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Tools</h4>
          <div className="space-y-2 text-xs text-neutral-400">
            <p><span className="text-cyan-400 font-medium">Teaching Assistant</span> &mdash; Chat with an AI tutor that responds to your questions and helps you think through problems.</p>
            <p><span className="text-cyan-400 font-medium">Canvas</span> &mdash; Whiteboard for diagrams, sketches, and visual thinking. Supports paste from clipboard.</p>
            <p><span className="text-cyan-400 font-medium">Notebook</span> &mdash; Scratchpad for writing down your thoughts, notes, and insights.</p>
            <p><span className="text-cyan-400 font-medium">Grokipedia</span> &mdash; Search external knowledge sources for background information on your topic.</p>
            <p><span className="text-cyan-400 font-medium">Practice</span> &mdash; Pre-session practice task. Auto-generates on first click.</p>
            <p><span className="text-cyan-400 font-medium">Theory</span> &mdash; Key concepts to review before or during your session. Auto-generates on first click.</p>
          </div>
        </div>

        {/* Utility Tools */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Utility Tools</h4>
          <div className="space-y-2 text-xs text-neutral-400">
            <p><span className="text-purple-400 font-medium">Help</span> &mdash; This guide.</p>
            <p><span className="text-purple-400 font-medium">Data Input</span> &mdash; Configure audio, EEG (Muse headset), and webcam inputs. View live audio levels, EEG band powers, and facial engagement metrics.</p>
            <p><span className="text-purple-400 font-medium">Logs</span> &mdash; Real-time data transfer health. Shows sent/saved/failed counts for audio, EEG, and facial data with status indicators.</p>
            <p><span className="text-purple-400 font-medium">RAG Matches</span> &mdash; Retrieves relevant chunks from your past sessions for the tutor to reference. A cyan dot appears when 3+ matches are found.</p>
          </div>
          <p className="text-xs text-neutral-600 mt-2">
            Help, Data Input, Logs, and RAG are always accessible even when the session is paused or not started.
          </p>
        </div>

        {/* Session Controls */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Session Controls</h4>
          <p className="text-xs text-neutral-500 mb-2">
            Use the <span className="text-neutral-300">Session</span> dropdown in the Student Monitoring header to manage your session.
          </p>
          <div className="space-y-1 text-xs text-neutral-400">
            <p><span className="text-neutral-300 font-medium">Start Session</span> &mdash; Begins audio recording and AI monitoring.</p>
            <p><span className="text-neutral-300 font-medium">Pause</span> &mdash; Pauses recording. Tools are locked until you resume.</p>
            <p><span className="text-neutral-300 font-medium">Resume</span> &mdash; Resumes recording and unlocks tools.</p>
            <p><span className="text-neutral-300 font-medium">Reset</span> &mdash; Clears all probes but keeps recorded data.</p>
            <p><span className="text-neutral-300 font-medium">Close</span> &mdash; Returns to dashboard without ending. Session can be resumed later.</p>
            <p><span className="text-neutral-300 font-medium">End Session</span> &mdash; Stops recording, saves all data, and goes to the results page.</p>
          </div>
        </div>

        {/* Student Monitoring */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Student Monitoring</h4>
          <div className="space-y-2 text-xs text-neutral-400">
            <p><span className="text-neutral-300 font-medium">Guiding Tasks</span> &mdash; AI-generated probes (questions, tasks, suggestions, checkpoints, feedback) that guide your learning. Up to 5 can be open at once. Archive them as you complete them.</p>
            <p><span className="text-neutral-300 font-medium">Session Plan</span> &mdash; Step-by-step roadmap. Steps advance automatically or you can mark them complete manually. You can also roll back to a previous step.</p>
            <p><span className="text-neutral-300 font-medium">Probe Slots</span> &mdash; 5 slots shown at the top. When all are full, the AI stops generating new probes until you archive some.</p>
            <p><span className="text-neutral-300 font-medium">Focus</span> &mdash; Click a probe to focus it. The AI will prioritize checking if focused probes are resolved.</p>
            <p><span className="text-neutral-300 font-medium">Suggested Tools</span> &mdash; Some probes suggest specific tools to try. Click the suggestions to switch to that tool.</p>
          </div>
        </div>

        {/* Pop-out & Mobile */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Pop-Out & Mobile</h4>
          <div className="space-y-2 text-xs text-neutral-400">
            <p><span className="text-neutral-300 font-medium">Pop Out</span> &mdash; Opens the Student Monitoring panel in a separate window. Useful for multi-monitor setups. All actions sync in real-time. Screen sharing is available in the pop-out window.</p>
            <p><span className="text-neutral-300 font-medium">Smartphone</span> &mdash; Opens a QR code you can scan to view probes and the session plan on your phone. Data syncs automatically.</p>
          </div>
        </div>

        {/* Panel Layout */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Panel Layout</h4>
          <div className="space-y-1 text-xs text-neutral-400">
            <p><span className="text-neutral-300 font-medium">Drag separator</span> &mdash; Resize the tools and monitoring panels.</p>
            <p><span className="text-neutral-300 font-medium">Hover separator</span> &mdash; Chevron buttons appear to collapse either panel to full width.</p>
            <p><span className="text-neutral-300 font-medium">Click collapsed strip</span> &mdash; Restore the panel to its previous width.</p>
            <p><span className="text-neutral-300 font-medium">Double-click separator</span> &mdash; Reset to 50/50 split.</p>
          </div>
          <p className="text-xs text-neutral-600 mt-2">
            Your panel layout is saved and restored across page loads.
          </p>
        </div>

        {/* How It Works */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">How It Works</h4>
          <ol className="text-xs text-neutral-400 space-y-1.5 list-decimal list-inside">
            <li>Create a session with a topic you want to learn.</li>
            <li>Start the session &mdash; your microphone begins recording.</li>
            <li>Think out loud. The AI listens and generates guiding tasks.</li>
            <li>Work through the probes using the tools (chat, canvas, notebook, etc.).</li>
            <li>Archive probes as you resolve them to make room for new ones.</li>
            <li>Follow the session plan steps or mark them complete manually.</li>
            <li>End the session when you feel confident. Review your results.</li>
          </ol>
        </div>

        {/* Data Inputs */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Data Inputs</h4>
          <p className="text-xs text-neutral-500 mb-2">
            Configure these in the Data Input tool. Only audio is required.
          </p>
          <div className="space-y-1 text-xs text-neutral-400">
            <p><span className="text-emerald-400 font-medium">Audio</span> &mdash; Microphone recording. Live audio levels shown when recording.</p>
            <p><span className="text-emerald-400 font-medium">EEG</span> &mdash; Muse headset via Bluetooth. Shows delta/theta/alpha/beta/gamma band powers and temporal waveforms.</p>
            <p><span className="text-emerald-400 font-medium">Webcam</span> &mdash; Facial engagement tracking (attention, confusion, emotion, gaze). No video is sent to the server.</p>
          </div>
        </div>

        {/* Keyboard Shortcut */}
        <div>
          <h4 className="text-sm font-medium text-white mb-2">Keyboard Shortcut</h4>
          <p className="text-xs text-neutral-400">
            <span className="px-1.5 py-0.5 rounded bg-neutral-800 border border-neutral-700 text-neutral-300 font-mono">Space</span>
            <span className="ml-2">Force a new probe while recording</span>
          </p>
        </div>

      </div>
    </div>
  );
}
